name: ui
description: "A new Flutter package project."
version: 0.0.1
homepage: stone.io
publish_to: none

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: